version: '3.8'
services:
  db:
    image: postgres:15
    container_name: orgax-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
volumes:
  db_data:
    name: orgax-db-data
